### ISSUE TITLE
iphone title不显示

### ISSUE THREAD

**Issue by mqliutie** [dreamochi/DayDayUp#43]
[iphone title不显示](http://www1.w3cfuns.com/blog-5437408-5409240.html)

**Comment by Somnusochi** [comment]
var setTitle = function(title) {
		var u = navigator.userAgent
		var isAndroid = u.indexOf('Android') > -1 || u.indexOf('Linux') > -1
		var isiOS = !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/)
		if (isAndroid) {
			document.title = title
		} else if (isiOS) {
			var $body = $('body')
			document.title = title
			var $iframe = $('<iframe src="/favicon.ico"></iframe>')
			$iframe.on('load', function() {
				window.setTimeout(function() {
					$iframe.off('load').remove()
				}, 0)
			}).appendTo($body)
		}
	}

**Comment by mqliutie** [comment]
```
var setTitle = function (title) {
    var u = navigator.userAgent;
    var isiOS = !!u.match(/(i[^;]+;( U;)? CPU.+Mac OS X/);
    document.title = title;
    if (isiOS) {
        var iFrame = document.createElement('iframe');
        iFrame.src = '../images/download/xiaoer.png';
        iFrame.style.display = 'none';
        iFrame.onload = function () {
            setTimeout(function () {
                iFrame.parentNode.removeChild(iFrame);
            }, 9)
        };
        document.body.appendChild(iFrame);
    }
};
```

**Comment by mqliutie** [comment]
此方法在最新版本微信上已失效

**Comment by mqliutie** [comment]
最新 **WKWebView** 已经支持 **document.title** 直接设置标题
